In [8]:
import numpy as np
import math

In [35]:
A = np.array([[1,2,4],[4, 2, 1]])
B = np.array([[4,3,0],[0, 3, 4]])
C = np.array([[3],[2],[2]])
print('A+B = \n', np.add(A,B))
print('A-B = \n', np.subtract(A,B))
print('A*B = \n', np.multiply(A,B)) # 对应元素相乘
print('A*B = \n', A*B)              # 对应元素相乘
print('A*C = \n', np.dot(A,C))      # 矩阵相乘 注意matmul的区别
print('A*C = \n', A.dot(C))
print('A*C = \n', A@C)              # 矩阵相乘

A+B = 
 [[5 5 4]
 [4 5 5]]
A-B = 
 [[-3 -1  4]
 [ 4 -1 -3]]
A*B = 
 [[4 6 0]
 [0 6 4]]
A*B = 
 [[4 6 0]
 [0 6 4]]
A*C = 
 [[15]
 [18]]
A*C = 
 [[15]
 [18]]
A*C = 
 [[15]
 [18]]


In [26]:
arr = np.arange(10)
arr_sqrt = np.sqrt(arr)
[arr_mod_decimal, arr_mod_int] = np.modf(arr_sqrt)


print(arr_sqrt)                     # 每个元素取平方根
print(arr_mod_decimal,arr_mod_int)       # 将小数部分[0]和整数部分[1]分开

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0.         0.         0.41421356 0.73205081 0.         0.23606798
 0.44948974 0.64575131 0.82842712 0.        ] [0. 1. 1. 1. 2. 2. 2. 2. 2. 3.]


In [34]:
arr_rand = np.random.randn(8, 8)
print(np.where(arr_rand > 0, 2, arr_rand))

[[ 2.         -0.73462353  2.         -1.13642849  2.          2.
   2.         -0.61519857]
 [ 2.         -0.3392453   2.          2.         -1.00828848  2.
  -0.05140458 -1.16907813]
 [ 2.          2.         -0.65324398  2.          2.         -0.33532022
  -0.44341776  2.        ]
 [ 2.         -1.35413115  2.         -1.81760452 -0.22653484 -0.95489554
  -0.62435672  2.        ]
 [-1.05073886 -1.25163806 -1.37941117  2.          2.          2.
  -0.20872961  2.        ]
 [ 2.          2.          2.          2.         -0.00692599  2.
  -1.20564606  2.        ]
 [-1.94273706  2.         -1.54415317  2.          2.          2.
   2.         -1.85214881]
 [ 2.         -0.61410827  2.          2.         -1.57464125 -2.11617517
  -2.13522294 -0.09437905]]


In [39]:
from numpy.linalg import inv, qr ## 矩阵运算

X = np.random.randn(5,5)
mat = X.T.dot(X) # X.T 代表 X转置

mat_inv = inv(mat)

mat.dot(mat_inv)

array([[ 1.00000000e+00, -5.91260775e-16,  2.58567023e-15,
        -8.15710440e-16,  1.11045895e-15],
       [ 8.77482142e-16,  1.00000000e+00,  4.98383229e-16,
         5.79814563e-16, -1.76509329e-15],
       [ 1.38131215e-17,  5.51803578e-16,  1.00000000e+00,
         7.06102036e-16,  4.83218871e-16],
       [ 9.82913406e-16, -1.14918666e-15,  7.20051750e-15,
         1.00000000e+00, -4.08815199e-15],
       [ 7.58005349e-16, -1.00664795e-15,  1.83597512e-15,
         9.86924131e-16,  1.00000000e+00]])